name: ci
on:
  push: { branches: [main] }
  pull_request:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install .[dev]
      - run: ruff check .
      - run: black --check .
      - run: mypy src
      - run: pytest -q
      - run: python -m pip install matplotlib
      - run: ./examples/ci_generate_artifacts.sh
      - uses: actions/upload-artifact@v4
        with:
          name: xi-vs-j
          path: artifacts/xi_vs_j.png
          if-no-files-found: error
      - name: Generate sweep plot
        run: python examples/benchmark_sweep.py
      - uses: actions/upload-artifact@v4
        with:
          name: xi-j-sweep
          path: artifacts/xi_j_sweep.png
          if-no-files-found: error
      - name: Commit docs images back to repo
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          mkdir -p docs
          cp -f artifacts/xi_vs_j.png docs/xi_vs_j.png
          cp -f artifacts/xi_j_sweep.png docs/xi_j_sweep.png
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/xi_vs_j.png docs/xi_j_sweep.png
          if git diff --cached --quiet; then
            echo "No doc image changes."
            exit 0
          fi
          git commit -m "docs: update Xi plots [skip ci]"
          git push origin "HEAD:${BRANCH_NAME}"
