name: ci
on:
  push: { branches: [main] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: python -m pip install .[dev]
      - run: ruff check .
      - run: black --check .
      - run: mypy src
      - run: pytest -q
      # Generate visualization artifact
      - run: python -m pip install matplotlib
      - run: ./examples/ci_generate_artifacts.sh
      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: xi-vs-j
          path: artifacts/xi_vs_j.png
          if-no-files-found: error
